/**
 * Photo Tournament — LIVING shared-Elo endpoint (Cloudflare Worker + Durable Object).
 *
 * A SEPARATE service from the git-commit results worker (worker/results-worker.js).
 * It backs the standalone live.html page: anyone can rank photos from the
 * "charlie-nature-photos" set into a single GLOBAL, living Elo. Every pick updates
 * the shared rating immediately and atomically. Rankers never receive Elo — only
 * the deliberate, terminal /leaderboard view exposes numbers.
 *
 * One Durable Object instance (idFromName == the set name) is the single source of
 * truth and the single serialized writer, so concurrent picks can never lose an
 * update. It bootstraps its starting Elo from the baked-in SEED (worker/seed/seed.js,
 * generated by scripts/build-seed.mjs) and never reads GitHub at runtime.
 *
 * Secrets (npx wrangler secret put …):
 *   ADMIN_TOKEN  — bearer token for POST /admin/reseed (optional; reseed disabled if unset)
 * Plain vars (wrangler.toml): ALLOWED_ORIGIN, SET
 *
 * Endpoints (all JSON):
 *   GET  /pair?sid=…   → { a:<cidx>, b:<cidx> }            (NO Elo; ids only)
 *   POST /pick         → { ok, applied, totalPicks }       (NO Elo)
 *   GET  /leaderboard  → { rows:[{cidx,name,elo,w,l,g}], … }  (the ONLY Elo surface)
 *   GET  /meta         → { v, fp, n, totalPicks }          (NO Elo; page-load gate)
 *   POST /admin/reseed → { ok, … }                         (Bearer ADMIN_TOKEN)
 */

import { SEED } from "./seed/seed.js";

// ── Elo constants (verbatim from app.js:19-20,331-339) ──
const START_RATING = 1000;
const K = 32;
function expected(a, b) {
  return 1 / (1 + Math.pow(10, (b - a) / 400));
}

const IDEMP_TTL_MS = 6 * 60 * 60 * 1000;   // remember pickIds this long (retry window)
const SESSION_TTL_MS = 30 * 60 * 1000;     // prune idle in-memory sessions after this
const MAX_SESSIONS = 2000;                  // LRU cap on in-memory sessions
const MAX_SEEN_PER_SESSION = 4000;          // cap a session's anti-rematch set
const MAX_SNAPSHOTS = 5;                    // reseed snapshot ring
const MAX_CONTRIB = 200;                     // cap contributor tally (bounds meta blob)

function json(obj, status) {
  return new Response(JSON.stringify(obj), {
    status: status || 200,
    headers: { "Content-Type": "application/json" },
  });
}
function pairKey(a, b) {
  return a < b ? a + "-" + b : b + "-" + a;
}
// Constant-time string compare (avoids leaking the admin token via timing).
function timingSafeEqual(a, b) {
  a = String(a); b = String(b);
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

// ─────────────────────────────────────────────────────────────────────────────
// Worker: CORS + route to the single Durable Object instance.
// ─────────────────────────────────────────────────────────────────────────────
export default {
  async fetch(request, env) {
    const ORIGIN = env.ALLOWED_ORIGIN || "https://chazlambo.github.io";
    const cors = {
      "Access-Control-Allow-Origin": ORIGIN,
      "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type, Authorization",
      "Vary": "Origin",
    };
    if (request.method === "OPTIONS") return new Response(null, { status: 204, headers: cors });

    const setName = env.SET || SEED.set;
    let res;
    try {
      const id = env.SHARED_ELO.idFromName(setName);
      const stub = env.SHARED_ELO.get(id);
      res = await stub.fetch(request);
    } catch (e) {
      return new Response(JSON.stringify({ error: "store unavailable" }), {
        status: 502, headers: { "Content-Type": "application/json", ...cors },
      });
    }
    // Re-wrap the DO response so every reply carries CORS headers.
    const headers = new Headers(res.headers);
    for (const k in cors) headers.set(k, cors[k]);
    return new Response(res.body, { status: res.status, headers });
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// Durable Object: the single living-Elo store + serialized writer.
// ─────────────────────────────────────────────────────────────────────────────
export class SharedElo {
  constructor(state, env) {
    this.state = state;
    this.env = env;
    this.sessions = new Map();                 // sid -> { seen:Set(pairKey), last }
    // Block all requests until storage is loaded / bootstrapped (no half-init reads).
    this.ready = state.blockConcurrencyWhile(() => this.init());
  }

  async init() {
    this.meta = await this.state.storage.get("meta");
    this.elo = await this.state.storage.get("elo");
    const seenArr = (await this.state.storage.get("seen")) || [];
    this.seen = new Map(seenArr);              // pickId -> ts (idempotency)

    if (!this.meta || !this.elo) {
      this.bootstrapFromSeed();
      await this.state.storage.put("meta", this.meta);
      await this.state.storage.put("elo", this.elo);
    }
  }

  bootstrapFromSeed() {
    const n = SEED.n;
    this.elo = {
      r: SEED.r.slice(),
      g: new Array(n).fill(0),
      w: new Array(n).fill(0),
      l: new Array(n).fill(0),
    };
    this.meta = {
      schemaV: 1,
      seedV: SEED.version,
      set: SEED.set,
      n,
      fingerprint: SEED.fingerprint,
      names: SEED.names.slice(),
      createdAt: Date.now(),
      lastWriteAt: 0,
      totalPicks: 0,
      contrib: {},                             // device -> { name, n }
    };
  }

  async fetch(request) {
    await this.ready;
    const url = new URL(request.url);
    const path = url.pathname.replace(/\/+$/, "") || "/";
    const m = request.method;
    if (m === "GET" && path === "/pair") return this.handlePair(url);
    if (m === "POST" && path === "/pick") return this.handlePick(request);
    if (m === "GET" && path === "/leaderboard") return this.handleLeaderboard();
    if (m === "GET" && path === "/meta") return this.handleMeta();
    if (m === "POST" && path === "/admin/reseed") return this.handleReseed(request);
    return json({ error: "not found" }, 404);
  }

  // ── sessions (in-memory, non-durable; safe to lose on eviction) ──
  session(sid) {
    sid = String(sid || "anon").slice(0, 64) || "anon";
    let s = this.sessions.get(sid);
    if (!s) {
      s = { seen: new Set(), last: Date.now() };
      this.sessions.set(sid, s);
      if (this.sessions.size > MAX_SESSIONS) this.evictSessions();
    }
    s.last = Date.now();
    return s;
  }
  evictSessions() {
    const cutoff = Date.now() - SESSION_TTL_MS;
    for (const [k, v] of this.sessions) if (v.last < cutoff) this.sessions.delete(k);
    if (this.sessions.size > MAX_SESSIONS) {
      const arr = [...this.sessions.entries()].sort((a, b) => a[1].last - b[1].last);
      const drop = arr.length - MAX_SESSIONS;
      for (let i = 0; i < drop; i++) this.sessions.delete(arr[i][0]);
    }
  }

  // ── pairing: least-played photo × nearest-rating opponent, avoid session rematch ──
  choosePair(sess) {
    const n = this.meta.n;
    const r = this.elo.r, g = this.elo.g;
    // (1) photo `a` weighted toward least-played (coverage).
    let total = 0;
    for (let i = 0; i < n; i++) total += 1 / (g[i] + 1);
    let t = Math.random() * total, a = 0;
    for (let i = 0; i < n; i++) {
      t -= 1 / (g[i] + 1);
      if (t <= 0) { a = i; break; }
      a = i;
    }
    // (2) partner `b`: nearest live rating not already seen this session.
    let b = -1, best = Infinity;
    for (let j = 0; j < n; j++) {
      if (j === a || sess.seen.has(pairKey(a, j))) continue;
      const d = Math.abs(r[a] - r[j]);
      if (d < best) { best = d; b = j; }
    }
    if (b < 0) {
      // Marathon: this session has seen everything paired with `a`. Reset its
      // memory and fall back to a random distinct partner rather than stalling.
      sess.seen.clear();
      do { b = Math.floor(Math.random() * n); } while (b === a);
    }
    return [a, b];
  }

  handlePair(url) {
    if (this.meta.n < 2) return json({ error: "set too small" }, 409);
    const sess = this.session(url.searchParams.get("sid"));
    const [a, b] = this.choosePair(sess);
    sess.seen.add(pairKey(a, b));
    if (sess.seen.size > MAX_SEEN_PER_SESSION) sess.seen.clear();
    return json({ a, b });
  }

  async handlePick(request) {
    let data;
    try { data = await request.json(); } catch (e) { return json({ error: "bad json" }, 400); }

    // Serialize the whole read-modify-write so concurrent picks can't interleave
    // or double-count. No `await` sits between reading and mutating this.elo.
    return this.state.blockConcurrencyWhile(async () => {
      const n = this.meta.n;
      const pickId = String(data.pickId || "").slice(0, 64);

      // (1) Idempotency FIRST — a retried/duplicated pick is a no-op success.
      if (pickId && this.seen.has(pickId)) {
        return json({ ok: true, applied: false, totalPicks: this.meta.totalPicks });
      }
      // (2) Integrity gate (authoritative): client must send a fingerprint +
      //     version that match this store, else its cidx may be stale (e.g. after
      //     a reseed). The real client always sends both, including via beacon.
      if (data.fp !== this.meta.fingerprint || String(data.v) !== String(this.meta.seedV)) {
        return json({ error: "set changed; reload", v: this.meta.seedV, fp: this.meta.fingerprint }, 409);
      }
      // (3) Validate the pick.
      const win = data.winner, los = data.loser;
      if (!Number.isInteger(win) || !Number.isInteger(los) ||
          win < 0 || los < 0 || win >= n || los >= n || win === los) {
        return json({ error: "bad pick" }, 400);
      }
      // (4) Compute new ratings into locals; reject wholesale if non-finite
      //     (poisoning guard) BEFORE touching the shared blob.
      const r = this.elo.r;
      const ew = expected(r[win], r[los]);
      const rWin = r[win] + K * (1 - ew);
      const rLos = r[los] - K * (1 - ew);
      if (!Number.isFinite(rWin) || !Number.isFinite(rLos)) {
        return json({ error: "non-finite result" }, 400);
      }
      // (5) Apply atomically (sync mutation).
      r[win] = rWin; r[los] = rLos;
      this.elo.w[win]++; this.elo.l[los]++;
      this.elo.g[win]++; this.elo.g[los]++;
      this.meta.totalPicks++;
      this.meta.lastWriteAt = Date.now();
      if (pickId) this.seen.set(pickId, Date.now());

      // contributor tally (the name gate's payoff). Only named devices count, and
      // the map is capped so a flood of fresh `device` ids can't grow meta forever.
      const dev = String(data.device || "").slice(0, 64);
      const nm = String(data.name || "").trim().slice(0, 40);
      if (dev && nm) {
        const c = this.meta.contrib[dev] || { name: nm, n: 0 };
        c.n++; c.name = nm;
        this.meta.contrib[dev] = c;
        const keys = Object.keys(this.meta.contrib);
        if (keys.length > MAX_CONTRIB) {
          // evict the least-active contributor (never the one we just touched)
          let drop = null, min = Infinity;
          for (const k of keys) {
            if (k === dev) continue;
            if (this.meta.contrib[k].n < min) { min = this.meta.contrib[k].n; drop = k; }
          }
          if (drop) delete this.meta.contrib[drop];
        }
      }
      // remember this duel for the contributing session's anti-rematch
      this.session(data.sid).seen.add(pairKey(win, los));

      // (6) Persist before responding (durable; eviction loses no votes).
      await this.state.storage.put("elo", this.elo);
      await this.state.storage.put("meta", this.meta);
      await this.persistSeen();

      return json({ ok: true, applied: true, totalPicks: this.meta.totalPicks });
    });
  }

  async persistSeen() {
    const cutoff = Date.now() - IDEMP_TTL_MS;
    for (const [k, ts] of this.seen) if (ts < cutoff) this.seen.delete(k);
    await this.state.storage.put("seen", [...this.seen.entries()]);
  }

  handleLeaderboard() {
    const n = this.meta.n, e = this.elo, names = this.meta.names;
    const rows = [];
    for (let c = 0; c < n; c++) {
      rows.push({ cidx: c, name: names[c], _r: e.r[c], elo: Math.round(e.r[c]), w: e.w[c], l: e.l[c], g: e.g[c] });
    }
    // sort matches app.js:469-471 (raw rating desc, wins desc, losses asc) — sort on
    // the UNROUNDED rating so near-ties don't reorder; round is for display only.
    rows.sort((a, b) => b._r - a._r || b.w - a.w || a.l - b.l);
    rows.forEach((row) => { delete row._r; });
    const contributors = Object.values(this.meta.contrib || {})
      .filter((c) => c.name)
      .map((c) => ({ name: c.name, n: c.n }))
      .sort((a, b) => b.n - a.n);
    return json({
      ok: true, v: this.meta.seedV, fp: this.meta.fingerprint, n,
      totalPicks: this.meta.totalPicks, updatedAt: this.meta.lastWriteAt,
      contributors, rows,
    });
  }

  handleMeta() {
    return json({
      ok: true, v: this.meta.seedV, fp: this.meta.fingerprint,
      n: this.meta.n, totalPicks: this.meta.totalPicks,
    });
  }

  // ── admin: re-seed from the (possibly updated) baked SEED, preserving the
  //    community's accumulated votes for surviving photos (joined by filename) ──
  async handleReseed(request) {
    if (!this.env.ADMIN_TOKEN) return json({ error: "admin disabled (no ADMIN_TOKEN set)" }, 403);
    const auth = request.headers.get("Authorization") || "";
    const token = auth.replace(/^Bearer\s+/i, "");
    if (!timingSafeEqual(token, this.env.ADMIN_TOKEN)) return json({ error: "unauthorized" }, 401);

    let body;
    try { body = await request.json(); } catch (e) { body = {}; }

    return this.state.blockConcurrencyWhile(async () => {
      if (String(body.confirm || "") !== String(this.meta.seedV)) {
        return json({ error: "confirm must equal current seedV", seedV: this.meta.seedV }, 409);
      }
      const ts = Date.now();
      // snapshot ring
      await this.state.storage.put(`snapshot:${this.meta.seedV}:${ts}`, { elo: this.elo, names: this.meta.names });
      await this.pruneSnapshots();

      // remap surviving r/g/w/l onto new cidx BY FILENAME; seed only new photos.
      const idxOf = new Map(this.meta.names.map((nm, i) => [nm, i]));
      const n = SEED.n, old = this.elo;
      const r = new Array(n), g = new Array(n), w = new Array(n), l = new Array(n);
      let carried = 0, fresh = 0;
      for (let c = 0; c < n; c++) {
        const oi = idxOf.get(SEED.names[c]);
        if (oi != null) {
          r[c] = old.r[oi]; g[c] = old.g[oi]; w[c] = old.w[oi]; l[c] = old.l[oi]; carried++;
        } else {
          r[c] = SEED.r[c]; g[c] = 0; w[c] = 0; l[c] = 0; fresh++;
        }
      }
      this.elo = { r, g, w, l };
      this.meta = {
        ...this.meta,
        seedV: SEED.version, n, fingerprint: SEED.fingerprint,
        names: SEED.names.slice(), lastWriteAt: ts,
      };
      await this.state.storage.put("elo", this.elo);
      await this.state.storage.put("meta", this.meta);
      return json({ ok: true, seedV: SEED.version, fingerprint: SEED.fingerprint, n, carried, fresh });
    });
  }

  async pruneSnapshots() {
    const keys = [...(await this.state.storage.list({ prefix: "snapshot:" })).keys()];
    if (keys.length > MAX_SNAPSHOTS) {
      // sort by the numeric trailing timestamp (seedV is free-form, not monotonic)
      keys.sort((a, b) => Number(a.split(":").pop()) - Number(b.split(":").pop()));
      for (let i = 0; i < keys.length - MAX_SNAPSHOTS; i++) await this.state.storage.delete(keys[i]);
    }
  }
}
